from kernel import BDDCombSim

Sim = BDDCombSim(5, 32)
Sim.init_basis_state(0)
Sim.H(0)
Sim.CNOT(0, 1)
Sim.CNOT(1, 2)
Sim.CNOT(2, 3)
Sim.H(0)
Sim.H(1)
Sim.H(2)
Sim.H(3)
Sim.CNOT(0, 4)
Sim.CNOT(1, 4)
Sim.CNOT(2, 4)
Sim.CNOT(3, 4)
Sim.print_state_vec()
Sim.measure([4], [1])
print('Finally, r = %d.' % Sim.r)
